### ISSUE TITLE
Regression in 6.2.0: ERROR TypeError: Cannot read property 'options' of undefined.

### ISSUE THREAD

**Issue by invidian** [cebor/angular-highcharts#193]
As @denishvachhani mentioned in the 4870ae5 comments, with this commit, it throws errors on destroy now.

Also https://github.com/cebor/angular-highcharts/commit/4870ae5833b107ec202676f2518eb73d51f9c52d#diff-a1fff436e7692a632911d77fcfee3f5aR99 is missing `;` at the end of the line.

**Comment by cebor** [comment]
Hi @invidian can you please post some errors or working code examples to reproduce this issue?

**Comment by cebor** [comment]
I also released `6.2.1` which should fix some errors.

**Comment by denishvachhani** [comment]
@cebor I will give a try and update you.

**Comment by invidian** [comment]
The problem still persists in `6.2.1`. Example code when it fails: https://github.com/finance-app/finance-ui/blob/master/src/app/transactions/transactions.component.ts#L144-L157

**Comment by cebor** [comment]
I had to fix another regression bug which affects the destroying. Can you please try `6.2.3`.

**Comment by cebor** [comment]
BTW: The Error being thrown would be nice.

**Comment by invidian** [comment]
It's still happening in `6.2.3`. Here is full stacktrace:
```
ERROR TypeError: Cannot read property 'initChart' of undefined
    at ChartDirective.push../node_modules/angular-highcharts/angular-highcharts.es5.js.ChartDirective.init (angular-highcharts.es5.js:59)
    at ChartDirective.push../node_modules/angular-highcharts/angular-highcharts.es5.js.ChartDirective.ngOnInit (angular-highcharts.es5.js:41)
    at checkAndUpdateDirectiveInline (core.js:8945)
    at checkAndUpdateNodeInline (core.js:10209)
    at checkAndUpdateNode (core.js:10171)
    at debugCheckAndUpdateNode (core.js:10804)
    at debugCheckDirectivesFn (core.js:10764)
    at Object.eval [as updateDirectives] (TransactionsComponent.html:8)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:10756)
    at checkAndUpdateView (core.js:10153)
```

So now the error message is different at least :)

**Comment by cebor** [comment]
@invidian looks like at some point your code put something in the directive which is not one of the following types: `Chart`, `StockChart`, `MapChart`.

The error occurs since `6.2.0` cause i have moved some code from the directive to the chart class method.

So when you always put in the correct type, it should have these method and should work.

I'm thinking about some extra type-checking inside my directive.

**Comment by cebor** [comment]
I released a new version `6.2.4` with type-checking in the directive, hope that this helps.

**Comment by invidian** [comment]
It seems to be fine with `6.2.6` :+1: Feel free to close it.
